### ISSUE TITLE
human body tracking

### ISSUE THREAD

**Issue by ekswathi** [FabianPlum/OmniTrax#1]
Is there any trained model for human body tracking?

**Comment by ekswathi** [comment]
face mainly

**Comment by FabianPlum** [comment]
That's a little more difficult with the current pipeline, but I'm planning on improving the pose estimation pipeline in the near future to include such options. 

This will however never be a full motion capture pipeline for human pose estimation and / or facial mocap for character animation specifically. Perhaps check out this approach:
https://blender.community/c/today/pQ5X/?sorting=hot

All the best
Fabi
