### ISSUE TITLE
[JOSS] Feedback on installation instructions

### ISSUE THREAD

**Issue by sfmig** [FabianPlum/OmniTrax#11]
Thanks for the detailed instructions, especially with the tricky CUDA bits! 

I really liked that enabling the addon nicely installs all the dependencies, and the screenshots and detailed steps will definitely make the tool accessible to a wider range of users.

I have some suggestions but none are vital, so feel free to take/leave them as you see fit.
- [x] #13
-  [x] #12
     - [here](https://github.com/UCL/Blender_Randomiser/tree/main?tab=readme-ov-file#installation-via-command-line) we did it with a bash and a Python script, but there may be better ways. 
- [x] #14
	- Since it is a bit lengthy, maybe it's a good idea to have a quick-guide in the README. This would just have the main steps (Blender, cuda, omnitrax addon, test run) and would link to a longer version with further details inside the docs.
	- Seeing the updates before the installation feels a bit confusing, since the first time you read it you lack sufficient context.
	- Maybe also adding separate sections for platform support (maybe as a matrix also showing GPU support?) and dependencies could make it all a bit clearer at a glance.
- [x] #15
    - I would suggest including a pointer to the Blender docs on [how to organise areas in a workspace](https://docs.blender.org/manual/en/latest/interface/window_system/areas.html).
    - It would also be nice to add a tip on how to define a workspace that persists. If people are gonna use this frequently for different projects it seems finicky to set up the workspace every time you launch Blender. I think workspaces are actually linked to a .blend file, so you'd need to define them as part of a Startup file (see [here](https://docs.blender.org/manual/en/latest/interface/window_system/workspaces.html#save-and-override))
    - You can use markdown [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for tips, they render nicely in Github.
    
- [x] #16

Hope this helps!

**Comment by FabianPlum** [comment]
Thanks a lot for all the great tips!
Implemented the majority of them, except for the option to install the addon via command line. 

As I want to keep things on a GUI level as much as possible, I'll leave this one out for now but will of course add documentation in the future if requested.
