### ISSUE TITLE
[Minor Item for Clarification] [Ubuntu 20.04] Warning when enabling Omnitrax on Blender 2.92

### ISSUE THREAD

**Issue by rizarae-p** [FabianPlum/OmniTrax#19]
Hi! Thanks for your hard work on this library. :)

I noticed this warning as I enabled omni_trax on Blender 2.92 in my Ubuntu system.

![Screenshot from 2024-02-28 14-32-58](https://github.com/FabianPlum/OmniTrax/assets/64082964/ab7ea767-57e0-44da-8f57-81c58656a2cf)

Just a minor comment but I think this warning message might confuse the users into installing Blender 3.3.0 for Ubuntu?

Please let me know your thoughts. :)

**Comment by FabianPlum** [comment]
Oh, great point! 
I'll update the system dependent Blender version-check right away!

**Comment by FabianPlum** [comment]
So unfortunately Blender reads out the `bl_info` from the `__init__.py` file as a literal, so I cannot trivially include any code that checks for the operating system first.

For now I'll therefore simply switch the requirement to "blender": (2, 92, 0). Windows users will likely not notice this change, as the value is not exposed to the user via the UI but Ubuntu users will at least not falsely be prompted with a version mismatch.

If this is flagged again in the future by Windows users having the opposite problem or I come across a reasonable automated check, I'll update the documentation and notes here accordingly.
