### ISSUE TITLE
[V0.2.2] Addon not detected after installing with zip file.

### ISSUE THREAD

**Issue by Seda145** [FabianPlum/OmniTrax#2]
If you install the addon from the zip file as instructed, it won't show up in the addon list.
It appears you need to have a folder directly within the zip file, for example "omni_trax" containing all the files before it will appear.

**Comment by FabianPlum** [comment]
Hi Seda!

Thanks a lot for giving OmniTrax a try! 
Could you let me know, how exactly you ran the installation?

If you download the [OmniTrax_v0.2.2 zip file from the releases](https://github.com/FabianPlum/OmniTrax/releases/download/V_0.2.2/omni_trax.zip) and tell Blender to install that, all should work correctly.

All the best
Fabi

**Comment by Seda145** [comment]
Hi Fabian, 

Figured out where it went wrong. The issue exists in a different version. The installation documentation speaks of 2.2 while linking to a v 2.0 in the text "Omnitrax" next to the 2.2 button.
![afbeelding](https://user-images.githubusercontent.com/30213433/236306324-629404a0-f64f-4663-a4f9-debae9eba015.png)

**Comment by Seda145** [comment]
Also: The download for version 0.2.2 displays as 0.2.1 within blender.

**Comment by FabianPlum** [comment]
Ah! Thanks for letting me know! The number is just not updated in the setup file. I'll fix that.
Apart from that, the add-on installation works now? 

If so, I'll close the issue with updating the version number and the readme link.

**Comment by Seda145** [comment]
yes, in 2.2 the zip contains a root folder, so it does show up just fine when picking the zip from within the blender addon panel. This issue can be closed.
