### ISSUE TITLE
[JOSS Review] Software Paper: State of the field

### ISSUE THREAD

**Issue by rizarae-p** [FabianPlum/OmniTrax#20]
Hi @FabianPlum! I've read through the paper, but I noticed there wasn't much discussion on this topic. Could you possibly include a bit more discussion on this particular point? 
> State of the field: Do the authors describe how this software compares to other commonly-used packages?

Thank you!

**Comment by sfmig** [comment]
Hi, 
Just to add a comment along these lines - would it be possible to expand a bit more on the buffer-and-recover approach to tracking, and why it is made possible with deep neural networks?
Thanks!

**Comment by FabianPlum** [comment]
Hi @rizarae-p and @sfmig!
I added a few more lines on comparable tracking approaches and the implementation here. I kept things brief for now, but if you feel more info is needed please let me know and I will re-open this issue!
