### ISSUE TITLE
[JOSS Review] Documentation: Statement of need

### ISSUE THREAD

**Issue by rizarae-p** [FabianPlum/OmniTrax#21]
Hi there! I believe the documentation could benefit from additional details regarding this topic, as mentioned in your software paper.

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Thank you!

**Comment by FabianPlum** [comment]
Hi @rizarae-p!

I added a few more details on whom the software is for and what example applications we have in mind. Please let me know if these additions suffice! I want to keep the text in the readme brief but you are absolutely right - it should nevertheless be comprehensive.

All the best
Fabi

**Comment by rizarae-p** [comment]
Yes, your revision looks great to me :)
