### ISSUE TITLE
[JOSS] Questions about dependencies

### ISSUE THREAD

**Issue by sfmig** [FabianPlum/OmniTrax#25]
Some questions about dependencies came up while reviewing:

- I was wondering if there is an alternative way of having the darknet/YOLO functionality with a PyPI package? My thinking is that otherwise it seems difficult to maintain (if they make updates we won't get them in omnitrax right?), but I'm not very familiar with vendoring. Would something like [this tool](https://pypi.org/project/vendorize/) help in that respect?
- I was also wondering why [a fork](https://github.com/AlexeyAB/darknet) of the repo is used, rather than [the original repo](https://github.com/pjreddie/darknet).
- If I understand correctly we are installing all the dependencies along the Python interpreter that ships with Blender - could we have conflicts if we install other add-ons with different requirements? Should users be warned about this?

**Comment by FabianPlum** [comment]
Hi @sfmig !
-	I agree, using the darknet integration does make things slightly more challenging to maintain, but for now, they make them fast and somewhat more controllable. I have been playing with the idea for a while to re-build this part of omnitrax to use a tensorflow implementaiton of YOLO instead, so removing further dependencies and keeping things in python altogether. As these changes are not trivial and OmniTrax functions well enough in its current state, I would only attempt to rebuild these elements if the number of users increases.

-	We are using a fork as YOLOv4 has canonically become the [successor of the original implementation by pjreddie](https://github.com/pjreddie/darknet?tab=readme-ov-file#yolov4). Models built and trained with the original code work just as well, but the work by Bochkovsky implementation is a little faster, adds additional activation functions, and data augmentation options.

-	Fair point - if people use other addons that rely on specific python libraries these may conflict. While this is somewhat universally true for blender addons that go beyond the scope of the pre-installed libraries, I agree, this potential issue should be made more apparent. I’ll add that to the warnings in the addon installation menu.

Let me know, if this addresses your questions!

**Comment by sfmig** [comment]
yes, all fantastically addressed! 🚀 thank you!
