### ISSUE TITLE
[JOSS] Suggestions on codebase structure

### ISSUE THREAD

**Issue by sfmig** [FabianPlum/OmniTrax#26]
The following are just suggestions but I think they could make it easier for external people to contribute. Feel free to take them or leave them as you please!

- I found the `__init__.py` file to be quite bloated - it makes it a bit difficult to inspect and contribute. I would suggest to refactor the classes into separate modules and only keep the register / unregister functions in the init file. We followed that approach in [this project](https://github.com/UCL/Blender_Randomiser/tree/main/randomiser) if you want to have a look. We also separated operators, properties and UI components into separate modules (and separately for different subpackages).

- Maybe consider having a few subpackages to group some of the modules that exist currently in root - this may make it easier for a contributor to identify at a glance which parts of the code are relevant for a specific feature/bug. For example, a `tracking` subpackage could include the modules`tracker.py`, `yolo_tracker.py` and `kalman_filter_new.py` maybe? Or maybe the cuda and package checks could be similarly grouped?

**Comment by rizarae-p** [comment]
I second this :)

**Comment by FabianPlum** [comment]
Agreed! I'll try to restructure everything tomorrow!
Thanks a lot for all your feedback

**Comment by rizarae-p** [comment]
May I ask if you could also run your codebase on ruff or flake8? They would give more tips on how to improve the entire code/codebase. :)

`pip install ruff`
`ruff check .`
or
`pip install flake8`
`flake8 .`

You can also use ruff to fix any formatting errors.
`ruff check . --fix    # Lint all files in the current directory, and fix any fixable errors.`

**Comment by FabianPlum** [comment]
Hi @sfmig and @rizarae-p!
I spent some time refactoring the code base today to improve the overall structure and readability of the code, based on your feedback and the structure outlined in [the referenced project](https://github.com/UCL/Blender_Randomiser/tree/main/randomiser).
I'll spend some more time early next week on updating doctstrings (#29) and parameter descriptions (#28), as well as some more general code cleanup (#30).

All the best and thanks a lot for your valuable feedback!
Fabi

**Comment by sfmig** [comment]
Hi Fabi,

The codebase is looking great! I think it's gonna be very useful for a lot of people.

I just had a quick go at running the tests locally in a linux machine (thanks for adding the steps! 🙌 ), and I got an error that looks like a refactoring side effect (`omni_trax.utils not found`). I didn't dig further but I figured I'd let you know just in case.

**Comment by FabianPlum** [comment]
Ah thanks for letting me know! I'll have a look first thing Monday morning

**Comment by FabianPlum** [comment]
Hi Sofia!

Everyone is asleep and I quickly wanted to fix the broken unit tests. I believe the issue crops up, when the repo is used on its own, instead of in the blender addon directory. I added some exception handling to help localise the correct project files which should resolve the problem and run the tests regardless of where they are located.

Hope this addresses your concerns!

All the best
Fabi

**Comment by sfmig** [comment]
Fantastic, thanks! Will have another go on Monday and let you know

**Comment by sfmig** [comment]
tests passing in my Ubuntu and Windows machines 🥳

**Comment by FabianPlum** [comment]
Hooray!!
