### ISSUE TITLE
[JOSS] Single animal pose estimation tutorial

### ISSUE THREAD

**Issue by sfmig** [FabianPlum/OmniTrax#27]
Hi,

I had a go at the [pose estimation full-frame tutorial](https://github.com/FabianPlum/OmniTrax/blob/main/docs/tutorial-pose-estimation.md#single-animal-pose-estimation) and am getting this error when selecting to export the data:

```
Using C:\Users\sminano\Downloads\VID_20220201_160304.mp4 for pose estimation...
Traceback (most recent call last):
  File "C:\Users\sminano\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\omni_trax\__init__.py", line 783, in execute
    pose_output_file.write(pose_joint_header_l1 + "\n")
UnboundLocalError: local variable 'pose_joint_header_l1' referenced before assignment
Error: Python: Traceback (most recent call last):
  File "C:\Users\sminano\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\omni_trax\__init__.py", line 783, in execute
    pose_output_file.write(pose_joint_header_l1 + "\n")
UnboundLocalError: local variable 'pose_joint_header_l1' referenced before assignment
```

This are my pose estimation parameters:
![image](https://github.com/FabianPlum/OmniTrax/assets/33267254/25881e17-3451-47e0-9f7f-19754edc3ff4)

I used the sample video provided ` VID_20220201_160304.mp4`

I also noticed the Blender file explorer that pops up when filling in the DLC model guides you to select a file, but actually we need to select only a folder. Maybe a clarification could be added to the tutorial, something like 'double click Accept to select the parent folder' ?

**Comment by FabianPlum** [comment]
Thanks a lot for the detailed description of the issue!
I fixed the (global) variable assignent and now the export should function correctly.

I'll try to make more progress on the other raised issues and code refactoring before adding a new release with all additions included!

Thank you so much for your time and dedication. Your comments have helped me a lot to make this repo more robust and slowly more maintainable as well!

**Comment by sfmig** [comment]
Sounds great! 
No worries, I'm glad it's been helpful! On my side it's been very fun to explore this tool 🤓
