### ISSUE TITLE
[JOSS] Functionality documentation: More verbose docstrings needed

### ISSUE THREAD

**Issue by rizarae-p** [FabianPlum/OmniTrax#29]
Hi @FabianPlum ! 'm nearly finished with the checks, but I've noticed the codebase could greatly benefit from more descriptive docstrings and some reformatting. To enhance consistency and readability, I recommend choosing a single docstring style—either Numpy, Google, or PEP257—that you feel best suits your project.

For implementing these improvements, `ruff` can be a good tool. 
You can configure `ruff` to enforce your chosen docstring style and other linting rules by creating a `pyproject.toml` file with the necessary settings. 
When you run `ruff check .`, it will automatically apply these configurations.

For more detailed instructions on setting up and using ruff, please see: https://pypi.org/project/ruff/0.0.221/.

**Comment by rizarae-p** [comment]
Hi @FabianPlum ! I just checked the current version now. Looks great!

**Comment by FabianPlum** [comment]
Thanks so much for your feedback and the super useful suggestions!

**Comment by rizarae-p** [comment]
No problem! Glad that I was able to help and I also had a lot of fun trying out your tool. :)
