### ISSUE TITLE
[V0.2.2] "Start tracking" crashes on CPU and GPU

### ISSUE THREAD

**Issue by Seda145** [FabianPlum/OmniTrax#3]
I installed the addon as administrator as instructed and used absolute paths for the pretrained yolo network. 
The addon shows a ticked checkbox which the instructions mention means a successful install.
Any attempt to track a video on the motion tracking workspace results in a crash.
CPU crash mentions it can't find some darknet cpu dll and gpu crashes to desktop.
Sorry for not being specific about the dll, i uninstalled blender for now and don't have that log.
Booting blender in debug mode shows me no related errors.

**Comment by Seda145** [comment]
installed blender 3.3.1 LTS + CUDA 11.2 + the right cudnn version. yolo network version YOLOv4-COCO-20230501T235200Z-001

**Comment by FabianPlum** [comment]
Hi Seda!

Could you let me know your system's specs (mostly RAM and GPU) and perhaps send me a link to the network configuration + weights that you are using?

As a quick test, could you try running some of the [videos](https://github.com/FabianPlum/OmniTrax/blob/main/docs/example_footage.md) and [example trained networks](https://github.com/FabianPlum/OmniTrax/blob/main/docs/trained_networks.md)?

Note that the CPU version with the provided DLLs will only run in Blender 2.92.

All the best
Fabi

**Comment by Seda145** [comment]
I have to retry this with version 0.2.2. Because of the 0.2.2 installation guide linking to 0.2.0 files I was unintentionally using 0.2.0 at the time of this problem.

**Comment by Seda145** [comment]
This specific crash does not occur in v0.2.2, can be closed
