### ISSUE TITLE
Example_scripts -> Tracking_Dataset_Processing -> Matplotlib error on appending Image

### ISSUE THREAD

**Issue by rizarae-p** [FabianPlum/OmniTrax#32]
Hi @FabianPlum ! Thanks again for your hardwork. Your new codebase looks great!
While testing the notebook Tracking_Dataset_Processing.ipynb, at the the last cell, I encountered this error on your image append.
My matplotlib version is 3.8.3.

![Screenshot from 2024-03-03 19-27-35](https://github.com/FabianPlum/OmniTrax/assets/64082964/1b50d97f-ed33-4b3a-9d64-2de43fbe6b89)

My proposed solution is to change  
`ax.images.append(im)`
to
`ax.add_image(im)`

Let me know what you think :)
Thanks! :)

**Comment by FabianPlum** [comment]
Done and done! 
Haven't ran into this issue before but your solution works well with my tested versions too
