### ISSUE TITLE
Multi-animal Pose Estimation Plot Skeleton is not working properly

### ISSUE THREAD

**Issue by rizarae-p** [FabianPlum/OmniTrax#33]
Hi @FabianPlum! :smile: 

I tested MA pose estimation on Omitrax using the test data you provided:
OS: Ubuntu 20.04
Video : multiple_ants_1920x1080_01.mp4 
YOLO Network : atta_single_class/yolov4-big_and_small_ants_320.cfg
DLC Network : DLC_ANT-POSE-MIXED_resnet_101_iteration-0_shuffle-1
With these parameters:
![Screenshot from 2024-03-03 20-34-40](https://github.com/FabianPlum/OmniTrax/assets/64082964/0aa50749-8a6a-4e44-a94e-515053ad2ceb)

and got this:
![Screenshot from 2024-03-03 20-27-00](https://github.com/FabianPlum/OmniTrax/assets/64082964/ffbeb344-f413-46dd-8e9f-ff36ad920dad)

Was wondering if this is also what you are getting?

Thank you :smile:

**Comment by FabianPlum** [comment]
Hi @rizarae-p!

Did you track the footage beforehand? The pose estimation step defaults to "full frame" pose estimation, when not bounding boxes from the tracking step are supplied.

**Comment by rizarae-p** [comment]
Oh yes, I missed that step! Thanks for clarifying! It's working now :heart:

**Comment by FabianPlum** [comment]
Oh, awesome! Thanks for letting me know
