### ISSUE TITLE
[JOSS] Animal research statement?

### ISSUE THREAD

**Issue by sfmig** [FabianPlum/OmniTrax#9]
According to [JOSS policy](https://joss.readthedocs.io/en/latest/policies.html#animal-research-policy):
> In the exceptional case a JOSS submission contains original data on animal research, the corresponding author must confirm that the data was collected in accordance with the latest guidelines and applicable regulations

Does this need to be added? 🤔 

I am not sure if the sample data shared in the repo is "original" (meaning, not published elsewhere), or if this applies to invertebrates, but it may just be adding a sentence to the readme... I saw in the replicAnt [paper](https://www.nature.com/articles/s41467-023-42898-9) there was no need for such statement so not sure it applies.

**Comment by FabianPlum** [comment]
Hi @sfmig! Thanks a lot for your critical eye here! 

Just like in the replicAnt paper, insects neither fall under European Directive 63/2010/EU, nor are any of the species shown in the video footage considered protected species under the Convention on International Trade in Endangered Species (CITES), so no specific permits were required.

As all footage is only here for demo purposes and stems from other studies, no video material was specifically collected for OmniTrax.

**Comment by rizarae-p** [comment]
Thanks for raising this. I am referencing these solved issues for my review as well. :)
